version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: whisper-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - api
    networks:
      - whisper-network
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: whisper-api
    environment:
      - NODE_ENV=production
      - PORT=3000
      - WHISPER_SERVICE_URL=http://whisper:8001
      - MAX_FILE_SIZE=100MB
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./api:/app
      - ./uploads:/app/uploads
      - ./logs/api:/app/logs
    depends_on:
      - whisper
    networks:
      - whisper-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3

  whisper:
    build:
      context: ./whisper
      dockerfile: Dockerfile
    container_name: whisper-service
    environment:
      - FLASK_ENV=production
      - MODEL_NAME=NbAiLabBeta/nb-whisper-small
      - DEVICE=cpu
      - CACHE_DIR=/app/cache
    volumes:
      - ./whisper:/app
      - ./uploads:/app/uploads
      - ./cache:/app/cache
      - ./logs/whisper:/app/logs
    networks:
      - whisper-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8001/health']
      interval: 60s
      timeout: 30s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G

networks:
  whisper-network:
    driver: bridge

volumes:
  uploads:
  cache:
  logs:
