name = "vegvisr-frontend"
compatibility_date = "2025-01-13"
main = "src/worker.js"

[build]
command = "npm run build"

# Assets configuration for static file serving
[assets]
directory = "./dist"
binding = "ASSETS"

# Optional: Environment-specific configuration
[env.preview]
name = "vegvisr-frontend-preview"
main = "src/worker.js"

[env.preview.build]
command = "npm run build"

[env.preview.assets]
directory = "./dist"
binding = "ASSETS"