name = "snowy-snow-5c75"          # Change this to your desired worker name

main = "index.js"                # Path relative to the wrangler.toml file (here, same folder)
compatibility_date = "2025-02-14"

# Optionally, if you plan to deploy to Workers.dev:
workers_dev = true

[[kv_namespaces]]
binding = "BINDING_NAME"
id = "1e3f20b8ed40453dbfa1f771012c99f2"